### ISSUE TITLE
Something to consider

### ISSUE THREAD

**Issue by jdalton** [dtao/lazy.js#1]
The cost of something like this [can be pretty high](http://jsperf.com/lazy-vs-lodash/2#chart=bar) for smaller collections:

Array of `20`
![capture1](https://f.cloud.github.com/assets/4303/503016/bbb00bfe-bcc0-11e2-8324-41bee3f14945.png)

and [gives mixed results](http://jsperf.com/lazy-vs-lodash#chart=bar) as the array length increases.

Array of `100`:
![capture](https://f.cloud.github.com/assets/4303/503019/ce4dba9a-bcc0-11e2-9cf1-c476d1a86bac.png)

I dig what you're trying to do, however it [may be better accomplished](http://jsperf.com/heya-pipe-loopers#chart=bar) through method compilation. For example checkout [heya/pipe](https://github.com/heya/pipe/).

**Comment by masaeedu** [comment]
The fundamental advantage of the library is the increase in the number of `no-op`s for equivalent computations.
