### ISSUE TITLE
Feature request: non-recursive flatten

### ISSUE THREAD

**Issue by djcsdy** [dtao/lazy.js#125]
I want to be able to join a sequence of sequences into a single sequence.

`flatten()` does this, but it does so recursively. I feel like most of the time this is the wrong design.

I would prefer a function that behaves like this:

```
Lazy([Lazy([1, 2]), Lazy([3])]).concatAll()
// -> sequence: [1, 2, 3]

Lazy([Lazy([Lazy([1, 2]), Lazy([3, 4])]), Lazy([Lazy([5, 6])])]).concatAll()
// -> sequence: [[1, 2], [3, 4], [5, 6]]

Lazy([Lazy([1, 2]), 3]).concatAll()
// error: '3' is not a sequence.
```

Unfortunately there doesn’t seem to be a good way of doing this with lazy.js at the moment.

I’m hoping that the reason that I want to be able to do this is self-evident, but if you want I can explain myself further. If I do be forewarned that there is a significant danger that I will start rambling about type theory :).

**Comment by akre54** [comment]
:+1: Underscore and Lodash both provide a "shallow" flag. Would be nice to have something like that here.

**Comment by djcsdy** [comment]
To be honest I’ve never really been sure what the use case is supposed to be for the recursive `flatten` in underscore, and why it is you have to set a flag to get the behaviour that I would have expected in the first place.

**Comment by nealeu** [comment]
:+1: I'd prefer not to overload flatten() with a flag.. which doesn't help conciseness nor readability.

**Comment by Announcement** [comment]
https://gist.github.com/Announcement/9d78ef7034b4605d5229
I wrote a flatten that doesn't use recursion, try implementating this into lazy.js?

**Comment by nealeu** [comment]
It's closing on for a year on this request?  Would you welcome a pull request??

**Comment by dtao** [comment]
@nealeu I always welcome pull requests :)

**Comment by Announcement** [comment]
has there been an associated pull request yet, or should I do it?

**Comment by nealeu** [comment]
@Announcement No. I've not raised one, drifted onto other priorities as so often happens.

**Comment by Announcement** [comment]
heres a pull request https://github.com/dtao/lazy.js/pull/208

**Comment by dtao** [comment]
Sorry for being so slow on this one. I can certainly add support for a "shallow" flag. That seems easiest.
