### ISSUE TITLE
Concat flattens arrays unexpectedly

### ISSUE THREAD

**Issue by djcsdy** [dtao/lazy.js#127]
```
Lazy([1,2])
    .concat(Lazy([3, [4,5]]))
    .toArray()
// Actual: [1, 2, 3, 4, 5]
// Expected: [1, 2, 3, [4, 5]]
```

I don’t think this is the expected behaviour.

FWIW, Underscore behaves as I expected:

```
_([1, 2]).concat([3, [4, 5]])
// Result: [1, 2, 3, [4, 5]]
```

The problem is that `ConcatenatedSequence` calls `flatten` internally, and `flatten` flattens the sequence recursively.

I think this illustrates my point in #125 quite well :-).

**Comment by flyingleafe** [comment]
+1

**Comment by queimadus** [comment]
+1

**Comment by dtao** [comment]
Yeah, this seems silly. I will take a look at fixing it.
