### ISSUE TITLE
How to instantiate StreamingHttpSequence ?

### ISSUE THREAD

**Issue by pavelvasev** [dtao/lazy.js#128]
Dear developers!

How can I create StreamingHttpSequence object in browser?
I tried with no luck: 

```
new StreamingHttpSequence()
new Lazy.StreamingHttpSequence()
```

and finished with 'back'-hack:

```
// insert into lazy.browser.js: 
  Lazy.makeHttpRequest = function (url) {
    return new StreamingHttpSequence(url);
  }
```

Could you please provide some "good" solution to create StreamingHttpSequence object?

**Comment by pavelvasev** [comment]
p.s. Even after that, calling
**Lazy.makeHttpRequest("myfile.txt").lines()** 
doesn't work. It throws exception in 
**SplitStreamSequence.prototype.stringEach**
saying that *'handle' is not defined*. 

It seems that StreamingHttpSequence.each method should return something like AsyncHandle?

**Comment by mmport80** [comment]
Also interested in this!

**Comment by formula1** [comment]
So [this](https://github.com/dtao/lazy.js/blob/master/lazy.browser.js#L163) is the http stream each. What I find interesting here is that listener is not returned.

[This](https://github.com/dtao/lazy.js/blob/master/lazy.js#L5049) is the Async Sequence which is the parent of StreamLike which is the parent of HTTP Sequence. It seems that The Async Sequence on "Each" Actually returns a handle which is an AsyncHandle.

Luckilly, AsyncHandle is available [here](https://github.com/dtao/lazy.js/blob/master/lazy.js#L5744), the api is available [here](https://github.com/dtao/lazy.js/blob/master/lazy.js#L5092) and an example is [here](https://github.com/dtao/lazy.js/blob/master/lazy.js#L5027).

I know this may sound like more work than you want, but if you try to

* Create an `var handle =  new Lazy.AsyncHandle()`
* Listen to the `request.addEventListener("error",handle._reject.bind(handle))`
* Add `handle._resolve()` to the abort part
* `return handle`

It might work. That being said, this is completely untested. I'm also interested in this, however I don't have time immediately to try and fix it. If you get it to work, send a pull request! :)

**Comment by dtao** [comment]
Pretty sure I was just an idiot and never exposed this.

I will fix the weird lack of return value and provide demo code in future commits.
