### ISSUE TITLE
Add new method Sequence.prototype.equals(otherSequence)

### ISSUE THREAD

**Issue by olsonpm** [dtao/lazy.js#139]
https://gist.github.com/olsonpm/3dad4232784d057d66c5

Right now the only sane way to compare the contents of two sequences is to first test that their length is equal then to zip them up and call .every(<equality function>).  The problem with that approach is that you're possibly iterating each sequence three times.  This function instead grabs each sequence's iterator then compares the two until they're either not equal, or one can iterate and the other can't.  In both of those cases, false will be returned - otherwise it returns 'true'.

Obviously it's possible to take an equality function, or a string which is assumed to an equality function property.  If no equality function is passed, it naturally defaults to strict equality between each element.

**Comment by dtao** [comment]
This all looks pretty good. I'm curious why you created a Gist, as opposed to submitting a pull request?

I also realize it's a bit late to be asking this question, as you opened this ticket 3 years ago! Maybe I'll take your code as inspiration and implement this in the near future.

**Comment by olsonpm** [comment]
Hi dtao, I was a very junior developer at that point, new to open source, git, github and javascript in general.  I appreciate your help back then because you were patient with me.

No worries about asking the question so late haha.  I just assume I created the gist because I didn't know what I was doing :)
