### ISSUE TITLE
Expose createCallback and equality in the public API

### ISSUE THREAD

**Issue by drslump** [dtao/lazy.js#140]
It'll be great if the `createCallback` function could be exposed outside the library so we can teach Lazy how to work with other libraries. The use case I want to solve is integrating [ass-ert](https://github.com/drslump/ass-ert) expressions with Lazy, it could work like this:

``` js
var oldCreateCallback = Lazy.createCallback;
Lazy.createCallback = function (obj) {
  if (ass.Chain.isChain(obj)) return obj.test;
  return oldCreateCallback(obj);
};

Lazy(persons)
.filter(ass.prop('age').above(18));
```

Ideally the equality comparison should also be exposed but looking at the source code it seems that Lazy prefers to use the native strict equality operator `===` probably for performance reasons. I think that overloading the `createCallback` most of the use cases can be solved anyway.

**Comment by dtao** [comment]
I'm actually not opposed to this idea at all—especially since `createCallback` is something I expect to be pretty stable (at least re: its behavior, if not its implementation).

I'll probably make this change for the next version.
