### ISSUE TITLE
<ObjectLikeSequence>.keys or .values breaks iterator

### ISSUE THREAD

**Issue by olsonpm** [dtao/lazy.js#141]
Due to ObjectLikeSequence.keys and values function turning its sequence into a MappingSequence, the iterator breaks upon iteration of either one.

Example:

```
var Lazy = require('lazy.js');

var a = Lazy({
    'akey': 'aval'
    , 'bkey': 'bval'
    , 'ckey': 'cval'
});

a.keys().each(function(k) {
    console.log(k); // prints akey, bkey, ckey as expected
});

var kit = a.keys().getIterator();
while (kit.moveNext()) {
    console.log(kit.current()); // prints 0, 1, 2
}

var vit = a.values().getIterator();
while (vit.moveNext()) {
    console.log(vit.current()); // prints [ 'akey', 'aval' ], ['bkey', 'bval'] ...
}
```

[The code found here](https://gist.github.com/olsonpm/df00ca2651c1dabd90a2) fixes the above, however I still haven't spent the time to figure out how to run existing tests in the repository.

**Comment by dtao** [comment]
Just FYI, to run the tests in the repository:

    npm test

**Comment by olsonpm** [comment]
Ah - guess I could have checked there first.
