### ISSUE TITLE
Testing for array

### ISSUE THREAD

**Issue by NN---** [dtao/lazy.js#146]
Instead of 'instanceof Array' function Array.isArray should be used.

``` javascript
var isArray = Array.isArray ? Array.isArray : function(a) { return a instanceof Array; };
```

**Comment by dtao** [comment]
I really have no opposition to this suggestion and was thinking about doing this. However, could you provide a bit of an explanation as to why `Array.isArray` is better? I'm really just curious—I'm aware of the method's existence, but honestly don't know why it's preferable.

One scenario I am aware of is that in some rare contexts (though I can't remember which) the `Array` global is redefined at some point, and so an actual array created before the re-definition fails `instanceof Array`—but as I said, I can't even remember when that happens (maybe it's when using the node repl?), or whether it's worth caring about.

Are there other situations where `instanceof Array` doesn't work but `Array.isArray` does? Or are there other reasons to prefer it?

**Comment by NN---** [comment]
In general Array.isArray is a standard and a preferable way for testing arrays.

The short story is passing arrays over frames.
The long story story is: http://web.mit.edu/jwalden/www/isArray.html
