### ISSUE TITLE
best way to prevent lazy.js operations from blocking the ui thread

### ISSUE THREAD

**Issue by olsonpm** [dtao/lazy.js#151]
So I tried using the AsyncSequence but unfortunately that only calls each iteration of the function passed to 'each'.  This means if it has to filter through 5000 results before it finds the next hit, then the UI thread is potentially blocked.  Right now I'm trying to debug this issue with a lagging loading gif on an iPhone 4s.

The only ideas I have right now are the following:

 - Create individual UI thread friendly versions of the sequences I need to use (e.g. sort and filter)
 - Try to extend lazy.js in such a way where the existing sequences can be told to only execute so many operations before yielding to the UI thread

I would greatly appreciate any other ideas.

**Comment by formula1** [comment]
WebWorkers!

Now, Lazy JS doesn't have webworker support by default, [but](http://www.html5rocks.com/en/tutorials/workers/basics/)...
1) If you put your lazy operation into a webworker `var bigdataOperation = new Worker("youOperation.js");
2) Run your lazy js with `.each(function(item){ self.postMessage(item) });
2) listen for items `worker.addEventListener('message', function(e) {
  yourItemHandlerInTheUI(e.data);
});

You can also create a wrapper for it

```
function LazyWorker(url){
  if(!(this instanceof LazyWorker)) return new LazyWorker(url);
  this.worker = new Worker(url);
}

LazyWorker.prototype.process = function(array){
  this.worker.postMessage({event:"obj",arg:[array]});
};

LazyWorker.prototype.each = function(cb){
  var self = this;
  this.worker.addEventListener('message', function(e) {
    cb(e.data);
  });
  this.worker.postMesssage({event:"each"});
}

LazyWorker.prototype.toArray = function(){
  var self = this;
  this.worker.addEventListener('message', function(e) {
    cb(e.data);
  });
  this.worker.postMessage({event:"toArray"});
}
```

```
//The Worker

var curvalues = void(0);
self.addEventListener('message', function(e) {
  switch(e.data.event){
    case "process": return curvalues = createYourLazySequence(e.data.arg[0]);
    case "toArray": return self.postMessage(curvalues.toArray()); self.close();
    case "each": 
      curvalues.each(self.postMessage.bind(self));
      return self.close();
  }
});

```

What this should allow for is
```
LazyWorker("yourLazyScript.js).each(function(item){  doSomethingWithTheUI(item) });

//or

LazyWorker("yourLazyScript.js).toArray(function(array){  
  //I hope you don't iterate more ;)
});
```


What this won't do is Allow you to have dynamic Queries. If this is something your interested in, you can create additional methods for that. Something like `LazyWorker.prototype.where = function(ob){ this.worker.postMessage({event:"where", arg:[ob]});};` should suffice. You just need to implement that on the otherside.

What you can also do is just make the any http requests and etc from within the webworker. In this manner you can make sure the UI thread avoids all Locks completely until the webworker has data to provide. I'd suggest using Each btw.

**Comment by olsonpm** [comment]
Wow - I'm surprised my googling yesterday didn't turn up this API.  I really appreciate the explanations and examples.  This definitely seems like a canonical solution.

**Comment by formula1** [comment]
Honestly, the webworld evolves so quickly and some technologies (i.e. Gamepad API) get swept under the rug if they aren't commonly used so I don't blame you. For what its worth, you may want to keep this open. Though webworker support isn't necessarilly a make or break feature in what already is an awesome and complex library. I'm confident other people would be interested in running an absurdly large array in a webworker as well
