### ISSUE TITLE
Sequence.async 's 'interval' definition is ambiguous

### ISSUE THREAD

**Issue by kenfdev** [dtao/lazy.js#153]
Hi, I'm a software engineer in Japan and pretty much new to Lazy.js but loving its feature so far.  I was using the `Sequence.async` and have a question about the definition of `interval` we can pass as a parameter.  The docs say `interval` is:

> The approximate period, in milliseconds, that should elapse between each element in the resulting sequence. Omitting this argument will result in the fastest possible asynchronous iteration.

I thought this meant that the first element's async process would start immediately whether or not you specify the `interval`.  Below is an example:

``` js
// 1st async
Lazy([1, 2, 3]).async(1000).each(function(e){
    console.log('1st async: ', e);
});

// 2nd async
Lazy([1, 2, 3]).async().each(function(e){
    setTimeout(function(){
        console.log('2nd async: ', e);
        }, 100);
});

// result(actual)
2nd async:  1
2nd async:  2
2nd async:  3
1st async:  1
1st async:  2
1st async:  3

// result(what I expected)
1st async:  1   // <- 1st async's 1st process starts 1st
2nd async:  1
2nd async:  2
2nd async:  3
1st async:  2
1st async:  3
```

Is this intended?  If so, I think it would have been better to say `interval` is:

> The approximate period, in milliseconds, that should elapse **before** each element in the resulting sequence. Omitting this argument will result in the fastest possible asynchronous iteration.

Am I missing something here?

Thanks in advance for any support.

**Comment by impinball** [comment]
Actually, it's a difference between this:

```coffee
# Your first example
Lazy [1, 2, 3]
  .async 1000
  .each (x) -> console.log "1st async: #{x}"

# Equivalent with Bluebird promises
log = (x) -> console.log "1st async: #{x}"

Promise.resolve null
  .delay 1000
  .then -> log 1
  .delay 1000
  .then -> log 2
  .delay 1000
  .then -> log 3
```

and this:

```coffee
# Your second example
Lazy [1, 2, 3]
  .async()
  .each (x) -> setTimeout (-> console.log "2nd async: #{x}"), 1000

# Equivalent with Bluebird promises
log = (x) -> console.log "2nd async: #{x}"

Promise.resolve null
  .then -> setTimeout (-> log 1), 1000
  .then -> setTimeout (-> log 2), 1000
  .then -> setTimeout (-> log 3), 1000
```

That help?

---

Also, you probably meant for the delay to be `1000` (note the extra 0) in your second example.

```js
// Your corrected second example
Lazy([1, 2, 3]).async().each(function(e){
    setTimeout(function(){
        console.log('2nd async: ', e);
        }, 1000);
});
```

That shouldn't affect the order of the result after the first of each, though.

**Comment by dtao** [comment]
I can definitely see how this would be confusing. For now, I think I'm just going to update the documentation to indicate that `interval` elapses before the first element in the sequence is iterated. I might be open to changing this behavior in the future.
