### ISSUE TITLE
Is Travis test for node v0.8 really necessary? 

### ISSUE THREAD

**Issue by markogresak** [dtao/lazy.js#156]
The version is relatively old and I doubt there is a lot of setups still using that version. It seems to fail to install some parts to make jasmine run the tests, therefore making whole Travis build fail with perfectly working code.
I would suggest removing `"v0.8"` from [`.travis.yml`](https://github.com/dtao/lazy.js/blob/master/.travis.yml#L5).
And while at it, it would be great to add `"iojs"`.

**Comment by impinball** [comment]
+1 for io.js. As for Node 0.8, I have no opinion.

**Comment by impinball** [comment]
And FWIW, the failing CI test is from a [`memorystream` failing to load](https://travis-ci.org/dtao/lazy.js/jobs/49197669#L303-L319), from a [non-existent `Stream.readable`/etc.](https://github.com/joyent/node/blob/v0.8/lib/stream.js) being passed to `util.inherits`. The test fix would be to conditionally load that module and associated tests, and not support them on Node 0.8, if that is to remain supported.

**Comment by dtao** [comment]
I'm fine not supporting Node 0.8. I wish there were some straightforward way to determine what libraries (or even applications) *depending* on lazy.js either support 0.8 or run on 0.8. But I don't know of any such way.

I would certainly like the build to pass again; and I don't think I'm really up for doing a lot of acrobatics to conditionally support certain things in certain environments. So I'll just drop 0.8.
