### ISSUE TITLE
JSON parsing confined to JSON arrays only?

### ISSUE THREAD

**Issue by pimpedoutgeek** [dtao/lazy.js#162]
I have read all of your doco including your blog content and the API DOCs.

I have studied the code @ lazy.browser.js and lazy.json.js

In particular I don't understand why the parsing of raw JSON is constrained to arrays only?

this.readValue() works but this.readObject() does not and I don't know why.

It would be great if there was an example using something like: Lazy.browser.StreamLikeSequence(url); where the url is a HTTP Request pointing to a source of raw, valid JSON that could be parsed just like your example in json.js does using the browser page to paste raw JSON array and is returned correctly parsed.

It seems any attempts to use anything Stream related fails without explanation.

**Comment by dtao** [comment]
JSON support is experimental at this point. Basically it's functionality that Lazy *could* support, and I made the demo to provide a sort of teaser as to how cool it would be; but unfortunately I haven't had the time to really invest in building it out fully.
