### ISSUE TITLE
Bug: `get` does not get the actual value when it's false

### ISSUE THREAD

**Issue by Redsandro** [dtao/lazy.js#170]
`false` is a distinct value for boolean, not the same as `null`.
But for `get`, `false` is assumed `undefined` and it will fall back to the default:

The `default` does not register for `get`, but it does for `value`.

```javascript
Lazy({ hasShotgun: false }).defaults({ hasShotgun: null }).value()
// Object {hasShotgun: false}
Lazy({ hasShotgun: false }).defaults({ hasShotgun: null }).get('hasShotgun')
// null
// EXPECTED:
// false
```

**Comment by Redsandro** [comment]
Perhaps more dramatically:

```javascript
Lazy({ "rm -rf": false }).defaults({ "rm -rf": true }).value()
// Object {rm -rf: false}
Lazy({ "rm -rf": false }).defaults({ "rm -rf": true }).get('rm -rf')
// true
```

**Comment by dtao** [comment]
Good catch! This appears to be a bug specific to the results of `assign` and `default`; I will fix.
