### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by daniell0gda** [dtao/lazy.js#171]
Hi,
I really like this library but why aren't you adding no typescript definitions? Typescript is very popular now and I personally am using only libs with definitions provided.

**Comment by bherila** [comment]
+1, I use Typescript as well and having d.ts definitions would be really helpful.

**Comment by ironside** [comment]
There are typings for LazyJS but not written by the author of the lib?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/lazy.js

TypeScript is the next best thing to Scala.

**Comment by daniell0gda** [comment]
it's for old version..

2015-11-06 14:43 GMT+01:00 Shawn <notifications@github.com>:

> There are typings for LazyJS but not written by the author of the lib?
> https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/lazy.js
>
> TypeScript is the next best thing to Scala.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtao/lazy.js/issues/171#issuecomment-154412786>.
>



-- 
Pozdrawiam,
Daniel Ferens

**Comment by msklvsk** [comment]
...and they can't infer type from `Iterable<T>`.

**Comment by CelsoSantos** [comment]
I too would like to add a request to have official TypeScript support/definitions.

Especially when it comes to Angular 2, 4 or whatever number we are at now..

**Comment by LoungeFlyZ** [comment]
Has anyone created a more up to date version of the type defs they can point me to?  This would be super helpful to have as part of the official repo.

**Comment by daniell0gda** [comment]
Sorry, cannot help you, I used lodash it has beautiful typescript definitions.

**Comment by bherila** [comment]
There hasn't been a commit in many months so I'd say look elsewhere, perhaps there is a more up-to-date fork

**Comment by dtao** [comment]
I'm not planning on doing anything with TypeScript in this library itself. If somebody else wants to own a TS port or adapter layer or something on top of Lazy.js, I'm supportive of that.

**Comment by aloifolia** [comment]
People who desire Typescript typings in their lazy-stream/sequence js library should take a look at [sequency](https://github.com/winterbe/sequency). It seems to have similar features to lazy.js, but is written in Typescript.
