### ISSUE TITLE
Each returns undefined after groupBy

### ISSUE THREAD

**Issue by nicemaker** [dtao/lazy.js#179]
I tried to group an array of objects and then run through the groups with each. What I was expecting is that I get either true or false, but I get undefined.

This is what I tried:

``` javascript
Lazy([
        {"type":"A","v":1},
        {"type":"A","v":4},
        {"type":"B","v":2},
        {"type":"B","v":1}
    ])
    .groupBy("type")
    .values()
    .each( n=>{ return true } );
```

Lazy is pretty new to me, so I am not 100% sure if this is a bug or if I am still missing some concepts.

**Comment by jrajav** [comment]
It looks like it is indeed a bug. The `values()` method returns a `GroupedSequence`, and `GroupedSequence.prototype.each()` returns `false` correctly when the `.each()` terminates early, but does not return `true` when it iterates through the full sequence.

**Comment by nicemaker** [comment]
I also had the problem with just using `groupBy` without `values`. I guess your fix on the `GroupedSequence.prototype.each()` will address that too, doesn't it?

**Comment by jrajav** [comment]
@nicemaker Yes, `.groupBy` also returns a GroupedSequence, so it will fix that case as well.
