### ISSUE TITLE
ObjectLikeSequence.defaults disables further defaults

### ISSUE THREAD

**Issue by AdamMcCormick** [dtao/lazy.js#183]
Calling the defaults method on a lazy object sequence sets "defaults" to an object so the following errors out:

```
lazy({test: "val"}).defaults({a: 'b'}).defaults({a: 'c', c: 'd'}).toObject()

VM65884:1 Uncaught TypeError: lazy(...).defaults(...).defaults is not a function(…)
```

I would have expected such internal values to be stored with an underscore so as not to obscure the defaults method. Instead I have to do a noop merge to get around this like so:

```
lazy({test: "val"}).defaults({a: 'b'}).merge({}).defaults({a: 'c', c: 'd'}).toObject()

Object {test: "val", a: "b", c: "d"}
```

Shouldn't both of those lines produce the same output?

**Comment by dtao** [comment]
Interesting. Taking a look now.

**Comment by AdamMcCormick** [comment]
Thank you! You rock
