### ISSUE TITLE
Lazy.Sequence isn't iterable

### ISSUE THREAD

**Issue by benmvp** [dtao/lazy.js#186]
First of all, great library! I just started using it and have been loving it so far! But I just ran into a stumbling block.

ES6/ES2015 introduced the concept of [_iterables_](http://www.benmvp.com/learning-es6-iterators-iterables/#iterables) to JavaScript. [`for-of`](http://www.benmvp.com/learning-es6-for-of-loop/), the [new collections](http://www.benmvp.com/learning-es6-new-collections/) (`Set`, `Map`, etc.), and [`Promise.all`](http://www.benmvp.com/learning-es6-promises/#promiseall) all use _iterables_ instead of explicit arrays.

You may already know this but the way to make an object _iterable_ is by implementing the default `@@iterator` method using the well-known `Symbol.iterator` symbol to return a JavaScript `Iterator`. Unfortunately the ES6 `Iterator` is different in its interface from `Lazy.Iterator` (see [interface](http://www.benmvp.com/learning-es6-iterators-iterables/#tldr)).

I think the fix may be as simple as extending `Lazy.Iterator` to conform to the JavaScript `Iterator` interface and then having `Lazy.Sequence` implement `Lazy.Sequence[Symbol.iterator]()`. Of course you would only do it if `Symbol.iterator` actually exists (in an ES6 environment).

It's something I can look into, but wanted to see if it's something desirable. 😄 

Thanks again!

**Comment by benmvp** [comment]
Forgot to mention that the whole reason I stumbled upon this issue is because I wanted to pass a `Lazy.Sequence` to `Promise.all()` and it complained that the object wasn't iterable. The obvious quick fix was to call `Lazy.Sequence.toArray()`, but I was trying to basically keep all of my objects as `Lazy` objects so that I'm not (unnecessarily) "serializing" & "parsing".

**Comment by dtao** [comment]
Great suggestion! It is definitely desirable from my perspective. I am happy to look into it, but from your comment it sounds like something you might like to try? (Then again, you posted this half a year ago so I certainly understand if you've moved on at this point.)

**Comment by dtao** [comment]
I played around a bit and then just went ahead and did this.

Now to figure out how to actually get this included in a way that doesn't break non-ES6 environments...

**Comment by benmvp** [comment]
Nice! That's basically what I was thinking! Couldn't have done it as quickly thought 😉
