### ISSUE TITLE
[Trivial-ish] Deciding on single conventional letter for Lazy

### ISSUE THREAD

**Issue by eshansingh** [dtao/lazy.js#187]
First of all I would like to say thanks to all the wonderful people who made and contributed to Lazy.js. It's an amazing library. 

However, I think the use of the name `Lazy` is a bit tedious, especially when compared to Underscore's... well.. underscore. The advantage of `Lazy`, though, is that it explicitly states that the operators are lazy. But I still think that we should decide on one letter, that, like `_`, should be used by most everyone who's using the library. It could be `l`, `@`, `~`, or whatever. 

Feedback? Suggestions?

**Comment by mattstyles** [comment]
Isn't this kind-of moot as the consumer can change the variable name to whatever they want?

```
const _ = require('lazy.js')
```

```
window._ = window.Lazy
```

Granted the 2nd method is pretty ugly but attaching to `window.Lazy` saves conflicts with lodash/underscore in the situation where someone wants to use both Lazy and lodash.

**Comment by eshansingh** [comment]
@mattstyles Yes, even with Lodash and Underscore this is moot (you can just say `let literallyAnything = _`, all I'm saying is we should decide on one letter, that, only by convention, is used as a short form for `Lazy`.

**Comment by nicolaiskogheim** [comment]
I see your point, @eshansingh. It would make it easier to understand Lazy code used other places if everyone uses the same shortcut, if any, instead of everyone having their own twist.

**Comment by misterhtmlcss** [comment]
The larger question seems to be for me looking from the outside in is whether this repo/project is even being actively worked on. Too bad as it seems to have some real potential, but nothing has been worked on in months. Am I wrong to assume this project is dead? I'm a newb, so maybe I'm not looking at the right signal regarding library legitimacy.
