### ISSUE TITLE
lazy.browser.js not in npm package

### ISSUE THREAD

**Issue by gavingolden** [dtao/lazy.js#190]
I'm a node/npm noob so forgive my trespasses. Is _lazy.browser.js_ supposed to be included in the npm package? If so, it looks like it isn't and I don't know how to add it. How can I go about this?

**Comment by dtao** [comment]
When this library was originally introduced it either wasn't common or I just wasn't _aware_ that it was common to use npm to manage dependencies for browser-based applications. So no, it isn't "supposed" to be included in the sense that I didn't intend for it to be included. That said, I was probably wrong then, and it certainly makes sense to include now.

As I stated in a different issue (#206), I need to revisit the matter of how this library is packaged for different environments soon. When I get to that I'll come back to this.
