### ISSUE TITLE
sum is unsuitable for use as string concatenation

### ISSUE THREAD

**Issue by excessivelyrigorous** [dtao/lazy.js#195]
sum [s0,s1,...,sn] behaves like
```
    lodash: s0+s1+...+sn
    lazy:   0+s0+s1+...+sn
```
As a consequence (using sum to perform string concatenation):
```javascript
    _.sum(["a"]) == "a"
    Lazy(["a"]).sum() == "0a"
```

**Comment by dtao** [comment]
I think I'm... OK with this. Why should a method called `sum` be suitable for string concatenation, especially when `join` is obviously *intended* for string concatenation?

Once again, my inclination is to simply update the docs to indicate that `sum` is intended for numeric values only, and that deviating from that will result in undefined behavior. Thoughts?

**Comment by excessivelyrigorous** [comment]
I think the relevant decision here is on how "well" Lazy.js should behave when used in an unintended way. 

When I think about that I get confused. It seems complicated.

I'm reporting some differences to LoDash because because of the claimed similarity of Lazy.js and LoDash. I do not necessarily mean to imply that Lazy.js is behaving poorly. That is not for me to decide.
