### ISSUE TITLE
indexOf/lastIndexOf when the argument is the empty string

### ISSUE THREAD

**Issue by excessivelyrigorous** [dtao/lazy.js#199]
Lazy.js will give a non-negative index when searching for the empty string, whereas lodash gives always -1
    e.g.:
```javascript
console.log(Lazy("abc").indexOf("")); // 0
console.log(Lazy("abc").lastIndexOf("")); // 3
```

Notice that in the second example, the returned index does not exist.
So we can get a non-negative index which is out of bounds; e.g.:

```javascript
var str = "abc";
var idx = Lazy(str).lastIndexOf("");
console.log(idx !== -1 ? str[idx] : "failure"); // undefined
```

Using indexOf instead will give "a" on the last line.
This violates the (proposed by me) invariants:

```
s[Lazy(s).indexOf(x)]     = y => x === -1 || x === y, for any string s, char x
s[Lazy(s).lastIndexOf(x)] = y => x === -1 || x === y, for any string s, char x
```

**Comment by dtao** [comment]
I have a hard time agreeing that this is a problem given that lazy.js is consistent with `String.protoype.indexOf` and `String.protoype.lastIndexOf` here:

```javascript
'foo'.indexOf('')
// 0

'foo'.lastIndexOf('')
// 3
```

I do appreciate the idea that these functions should be reversible in the sense that if you try to access a string at the index you get, you'll get the value you passed in.

...but wait, that's not really right, is it? Accessing a string by index always returns a _single character_, so the above rule only applies if you've passed in a string with `length == 1`. A better *general* rule would be that whatever you get back from `indexOf`/`lastIndexOf` you could pass into `substring`:

```javascript
var assert = require('assert');

function verify(haystack, needle) {
    var index = haystack.indexOf(needle);
    if (index != -1) {
        assert(haystack.substring(index, index + needle.length) == needle);
    }

    var lastIndex = haystack.lastIndexOf(needle);
    if (lastIndex != -1) {
        assert(haystack.substring(lastIndex, lastIndex + needle.length) == needle);
    }
}

verify('foo', 'o');
verify('foo', 'foo');
verify('foo', 'bar');
verify('foo', '');
```

**Comment by excessivelyrigorous** [comment]
I agree with this. What I wrote silently assumes length 1 of the input string as you say. My bad.

Given the consistancy with String.prototype I think there is nothing more to do here.

Still it seems weird to me on a level higher than the specific programming language.
So we have as expected that
1. the empty string is the substring of any string.
2. But we also have that the empty string has every index of every string.

**Comment by dtao** [comment]
I agree that it is weird... but not *that* weird ;)

I think of it sort of in terms of sets. Every set includes the empty set. As for the substring thing, the weird part is probably not so much the behavior as the fact we want to define the behavior at all.
