### ISSUE TITLE
omit ignores keys in {true, false}

### ISSUE THREAD

**Issue by excessivelyrigorous** [dtao/lazy.js#200]
omit ignores keys in {true, false}, unlike lodash. Keys in {'true', 'false'} are ok.
e.g.:
```javascript
var arr0 = [false, true, 'k'];
var arr1 = ['false'];
Lazy(   {false: 'a', true: 'b', k: 'c'}).omit(arr0) // { false: 'a', true: 'b' }
_.omit( {false: 'a', true: 'b', k: 'c'},      arr0) // {}
Lazy(   {false: 'a', true: 'b', k: 'c'}).omit(arr1) // { true: 'b', k: 'c' }
_.omit( {false: 'a', true: 'b', k: 'c'},      arr1) // { true: 'b', k: 'c' }
```

**Comment by dtao** [comment]
I'm torn on this one. I get that lodash behaves differently, but is that really right?

The main concern I have is that what you are proposing as the desired behavior seems to want devs to be able to pretend that any value can be used as a key in an object, when the reality isn't so. For instance, what should happen here?

```javascript
Lazy({true: 1, 'true': 2}).omit('true').toObject();
```

Wouldn't you think (from your examples) that the above should result in `{true: 1}`? But that isn't possible:

```javascript
var obj = {true: 1, 'true': 2}
// { true: 2 }

Object.keys(obj)
// [ 'true' ]
```

I'm sure I haven't been super consistent about this, but generally I think I'd like for lazy.js not to fudge the underlying data or do any unexpected (to me) type coercion. So for *me* the fix here would probably be to simply update the documentation for `omit` to make it clear that keys must be strings.

All that said, I'm sure I could be convinced I'm wrong. Do you strongly disagree?

**Comment by excessivelyrigorous** [comment]
I prefer Lazy.js behavior here. Maybe I should take the issue to LoDash? :)

**Comment by dtao** [comment]
Ha, if you want. For the record it is not an explicit goal (in my mind—I should probably clarify this somewhere) for lazy to match underscore or lodash *exactly*. In some places I've intentionally deviated from these libraries, for example in the signature of the `each` method. In other places—like this one—the discrepancy wasn't intentional on my part, but when you point it out to me I might prefer lazy's behavior.
