### ISSUE TITLE
Are `take` and `drop` deprecated ?

### ISSUE THREAD

**Issue by foisonocean** [dtao/lazy.js#203]
I can't find `take` and `drop` in the [doc](http://danieltao.com/lazy.js/docs/), are they deprecated ?

So if I want to drop the first item and the last item in a sequence, how can I do ?

**Comment by dtao** [comment]
No, they're not deprecated: `take` is simply an [alias for `first`](http://danieltao.com/lazy.js/docs/#Sequence-first), and `drop` is likewise an [alias for `rest`](http://danieltao.com/lazy.js/docs/#Sequence-rest).

I plan to improve the docs to include these items at the top level.
