### ISSUE TITLE
Publish the library to npm registry

### ISSUE THREAD

**Issue by x1unix** [dtao/lazy.js#210]
Please add link to the `npm` package at `README`

P.S - I recommend to publish it under private namespace (`@dtao/lazyjs`) because there are a lot of libraries there with the same name (`lazy`, `lazy-js`)

**Comment by dtao** [comment]
This library is already published as lazy.js (with the dot).

I know, it's weird; and you're right, there are lots of packages with similar names. To be fair the README has `require('lazy.js')` right in there. But I suppose installation instructions might still be useful. I can add them.
