### ISSUE TITLE
uniq function definition 

### ISSUE THREAD

**Issue by JustasKuizinas** [dtao/lazy.js#213]
Instead of 
```
  uniq(): Sequence<T>;
```
Shouldn't definition look like?
```
  uniq(something:string): Sequence<T>;
```
because I am getting error 'Suplied parameters do not match any signature of call target'.

**Comment by dtao** [comment]
Hmm, what is giving you that error? The `uniq` method takes an *optional* `keyFn` parameter. It looks like you might be using some build system that doesn't like the way it's implemented, maybe?

**Comment by dtao** [comment]
I updated the doc for `uniq` to indicate that the `keyFn` argument is optional. That said, I'm not sure what build tool you're using that was giving you this error; so I don't know if this resolves the issue from your perspective. From _my_ perspective, Lazy.js makes no commitment to work nicely with any particular external build tool.
