### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ShawnTalbert** [dtao/lazy.js#216]
Looks like there's been no significant activity for a year. Too bad since this was the only implementation I found that treated Sequences as a first class citizen (and hence all the associated power).

Do I have to switch to using a combination of multiple libraries - e.g. lodash as utility belt + RxJS or IxJS or something for first class Sequences?

**Comment by dtao** [comment]
It's not dead! I just work on it on an incredibly inconsistent and sporadic basis. If you're not comfortable depending on it for that reason (which would be quite reasonable), then you might prefer to look elsewhere.

**Comment by dtao** [comment]
For what it's worth, I'll be releasing a new version in the next week.
