### ISSUE TITLE
Calling map() on an ObjectLikeSequence takes a function with (value, key) parameters instead of (tuple) parameters?

### ISSUE THREAD

**Issue by demands** [dtao/lazy.js#46]
In the most recent version of lazy.js, we were able to use it like this:

``` javascript
lazy({a:1, b:2, c:3})
  .map(function(tuple) { return tuple.join('='); })
  .toArray()

  // => ["a=1", "b=2", "c=3"]
```

Seems like now the pattern is:

``` javascript
lazy({a:1, b:2, c:3})
  .map(function(value, key) { return [key, value].join('='); })
  .toArray()

  // => ["a=1", "b=2", "c=3"]
```

This makes some sense, but it doesn't seem to be documented/tested anywhere? It's also possible we're missing something. Either way, this broke a lot of our code :( (early adopter woes, I know.)

FWIW, we use lazy with coffeescript, where the tuple syntax actually says a lot about the underlying representation of the lazy sequence we're working with. Example:

``` coffeescript
lazy(a:1, b:2, c:3)
  .map ([key, value]) ->
    "#{key}=#{value}"
  .toArray()

  # => ["a=1", "b=2", "c=3"]
```

Thanks again for the library, it's extremely useful and keeps us lazy.

**Comment by dtao** [comment]
Well, I'm not sure why I didn't close this issue. Yes, `map()` now takes a function that accepts `(value, key)` arguments for `ObjectLikeSequence` or `(value, index)` for `ArrayLikeSequence`.
