### ISSUE TITLE
Benchmark jquery

### ISSUE THREAD

**Issue by ghost** [dtao/lazy.js#47]
I like your benchmark personally and I would like to see a comparison to jquery as well. Now I know jquery does not exactly fulfill the same purpose, but there is some common ground and a comparison of whats comparable between jquery and the others would be nice.

**Comment by dtao** [comment]
I'm not going to do this. I think the libraries are different enough there is no real point in comparing them in whatever little overlap exists.

Moreover, I intend to de-emphasize comparisons with other libraries in general. I don't have a specific timeline in mind for that, but it'll be some time before Lazy hits 1.0.
