### ISSUE TITLE
Is it possilble to have Lazy.events (Event sequences) for value change?

### ISSUE THREAD

**Issue by kenokabe** [dtao/lazy.js#49]
lazy.js is one of the best project I've ever found.
This library integrates undersocre/linq.js and RxJS with lazy evaluation advantage where I feel that a clean and complete implementation of Functional/Declarative programming paradigm is deployed;  All the JS programmers should learn from this.
Thank you, Dan Tao.

Having said that, I have a question:
Basically, I want to bind javascript value with DOM element behavior.

To monitor `myval` change event, I could  code something like:

```
var monitor = function()
{
  if(myval != myval0)
  {
      triggerEach(); // function to manipulate DOM 
  }
  myval0 = myval;
}
var tid = setInterval(function()
{
    monitor();
},100);
```

Is it possilble to have Lazy.events like this??

**Comment by dtao** [comment]
Well, it looks like `Object.observe` is [not a thing anymore](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe).

I'm going to close this issue as `watch()` is a feature that [has been documented](http://danieltao.com/lazy.js/docs/#ObjectLikeSequence-watch) awhile. It's a bit weird, and I might like to change how it works in the future; but for now, it's there and it works.
